import { Shipment } from '../types/shipment';

export const MOCK_SHIPMENTS: Shipment[] = [
    {
        id: 'shp-101',
        orderNumber: '#STK-48291',
        customerName: 'Sarah Khan',
        customerPhone: '+92 300 5550192',
        customerEmail: 'sarah.k@example.com',
        carrier: 'dhl',
        trackingNumber: 'DHL-984210398',
        currentStatus: 'DELIVERY_EXCEPTION',
        isException: true,
        exceptionReason: 'Package held at sorting facility (No scan for 52 hours)',
        transitDays: 4,
        lastScan: '2 hours ago',
        destination: 'Lahore, PK',
        riskScore: 88,
        riskLevel: 'CRITICAL',
        estimatedExposure: 240,
        trackingLogs: [
            { id: 'l1', rawStatus: 'Shipment Created', normalizedStatus: 'LABEL_CREATED', location: 'Karachi Hub', timestamp: 'Aug 11, 09:00 AM' },
            { id: 'l2', rawStatus: 'In Transit to Regional Sorting', normalizedStatus: 'IN_TRANSIT', location: 'Highway Transit', timestamp: 'Aug 12, 02:30 PM' },
            { id: 'l3', rawStatus: 'Shipment held at destination facility', normalizedStatus: 'DELIVERY_EXCEPTION', location: 'Lahore Hub', timestamp: 'Aug 13, 10:32 AM' },
        ],
    },
    {
        id: 'shp-102',
        orderNumber: '#STK-48292',
        customerName: 'Marcus Vance',
        customerPhone: '+1 415 555 0184',
        customerEmail: 'marcus.v@example.com',
        carrier: 'fedex',
        trackingNumber: 'FX-884920194',
        currentStatus: 'FAILED_ATTEMPT',
        isException: true,
        exceptionReason: 'Customer unavailable at provided address',
        transitDays: 3,
        lastScan: '45 mins ago',
        destination: 'Austin, TX',
        riskScore: 76,
        riskLevel: 'HIGH',
        estimatedExposure: 180,
        trackingLogs: [
            { id: 'l10', rawStatus: 'Picked Up by Courier', normalizedStatus: 'IN_TRANSIT', location: 'Austin Dispatch', timestamp: 'Aug 14, 08:00 AM' },
            { id: 'l11', rawStatus: 'Delivery Attempted - Recipient Unreachable', normalizedStatus: 'FAILED_ATTEMPT', location: 'Austin, TX', timestamp: 'Aug 15, 01:15 PM' },
        ],
    },
    {
        id: 'shp-103',
        orderNumber: '#STK-48293',
        customerName: 'Elena Rostova',
        carrier: 'trax',
        trackingNumber: 'TRX-7740219',
        currentStatus: 'OUT_FOR_DELIVERY',
        isException: false,
        transitDays: 2,
        lastScan: '15 mins ago',
        destination: 'Islamabad, PK',
        riskScore: 18,
        riskLevel: 'LOW',
        trackingLogs: [
            { id: 'l20', rawStatus: 'Out for final mile delivery', normalizedStatus: 'OUT_FOR_DELIVERY', location: 'Islamabad Hub', timestamp: 'Aug 15, 08:30 AM' },
        ],
    },
    {
        id: 'shp-104',
        orderNumber: '#STK-48294',
        customerName: 'David Chen',
        carrier: 'leopard',
        trackingNumber: 'LPD-4491023',
        currentStatus: 'IN_TRANSIT',
        isException: false,
        transitDays: 1,
        lastScan: '3 hours ago',
        destination: 'Rawalpindi, PK',
        riskScore: 22,
        riskLevel: 'LOW',
        trackingLogs: [
            { id: 'l30', rawStatus: 'Departed Sorting Facility', normalizedStatus: 'IN_TRANSIT', location: 'Rawalpindi North', timestamp: 'Aug 15, 12:00 PM' },
        ],
    },
    {
        id: 'shp-105',
        orderNumber: '#STK-48295',
        customerName: 'Amara Patel',
        carrier: 'dhl',
        trackingNumber: 'DHL-1192049',
        currentStatus: 'DELIVERED',
        isException: false,
        transitDays: 2,
        lastScan: '1 day ago',
        destination: 'London, UK',
        riskScore: 5,
        riskLevel: 'LOW',
        trackingLogs: [
            { id: 'l40', rawStatus: 'Delivered and Signed', normalizedStatus: 'DELIVERED', location: 'London SW1', timestamp: 'Aug 14, 04:20 PM' },
        ],
    },
];
